variables:
    POI_IMAGE_NAME: photon/installer:$CI_COMMIT_SHORT_SHA

stages:
- build
- test

build-container:
  stage: build
  script:
    - cd docker && docker build -t ${POI_IMAGE_NAME} --build-arg DOCKER_PROXY=dockerhub.artifactory.eng.vmware.com/ --build-context poi-helper=$(realpath $(pwd)/..) .
    - docker system prune -f

pytest:
  stage: test
  script:
    - pytest-3 -x tests/poi-container-test.py
