variables:
    POI_IMAGE_NAME: photon/installer:$CI_COMMIT_SHORT_SHA
    GITHUB_BRANCH: $CI_DEFAULT_BRANCH

stages:
- build
- test
- github

build-container:
  stage: build
  script:
    - cd docker && docker build -t ${POI_IMAGE_NAME} --build-arg DOCKER_PROXY=dockerhub.artifactory.eng.vmware.com/ --build-context poi-helper=$(realpath $(pwd)/..) .
    - docker system prune -f

cayman_poi:
    stage: build
    script:
        - gitlab --private-token=$CAYMAN_POI_CICD_API_TOKEN project-branch create --project-id core-build/cayman_photon-os-installer --branch test/poi-submodule/$CI_COMMIT_SHORT_SHA --ref vmware-master
        - gitlab --private-token=$CAYMAN_POI_CICD_API_TOKEN project update-submodule --id core-build/cayman_photon-os-installer --branch test/poi-submodule/$CI_COMMIT_SHORT_SHA --submodule poi/src --commit-sha $CI_COMMIT_SHA

pytest:
  stage: test
  script:
    - pytest-3 -x tests/poi-container-test.py

github:
    stage: github
    rules:
        # only for the master branch
        - if: $CI_COMMIT_REF_NAME == $GITHUB_BRANCH
    variables:
        # need clone strategy or adding a remote will fail if it exists
        GIT_STRATEGY: clone
        GITHUB_USER: gerrit-photon
    script:
        - git checkout $CI_COMMIT_REF_NAME
        - git remote add github https://$GITHUB_USER:$GERRIT_PHOTON_GITHUB_TOKEN@github.com/vmware/photon-os-installer.git
        - git push github
