variables:
    POI_IMAGE_NAME: photon/installer:$CI_COMMIT_SHORT_SHA

stages:
- build
- test

build-container:
  stage: build
  tags:
    - docker
  script:
    - cd docker && docker build -t ${POI_IMAGE_NAME} --build-arg DOCKER_PROXY=harbor-repo.vmware.com/dockerhub-proxy-cache/ --build-context poi-helper=$(realpath $(pwd)/..) .
    - docker system prune -f

pytest:
  stage: test
  tags:
    - shell
  script:
    - pytest-3 -x tests/poi-container-test.py