stages:
- build

build-container:
  stage: build
  services:
    - name: harbor-repo.vmware.com/dockerhub-proxy-cache/library/docker:dind
      alias: docker
  script:
    - cd docker && docker build -t photon-os-installer --build-arg DOCKER_PROXY=harbor-repo.vmware.com/dockerhub-proxy-cache/ --build-context poi-helper=$(realpath $(pwd)/..) .
